// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMjqYbNPp7rv4vYySMJvUbO-3bXh1gMtQ',
    appId: '1:19763097480:web:85fdb02d47b1f5fe86543d',
    messagingSenderId: '19763097480',
    projectId: 'univalle-news-11560',
    authDomain: 'univalle-news-11560.firebaseapp.com',
    storageBucket: 'univalle-news-11560.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtfmhgU2iEiV2b3YPvvfcyGWcLpszZxRI',
    appId: '1:19763097480:android:1d3bf9e6b208ac0b86543d',
    messagingSenderId: '19763097480',
    projectId: 'univalle-news-11560',
    storageBucket: 'univalle-news-11560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIdOK6vrQBAXO0Hm3y6UcSYVLRwMLQpzI',
    appId: '1:19763097480:ios:f6d0e79e2385c78f86543d',
    messagingSenderId: '19763097480',
    projectId: 'univalle-news-11560',
    storageBucket: 'univalle-news-11560.appspot.com',
    iosBundleId: 'com.example.univalleNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIdOK6vrQBAXO0Hm3y6UcSYVLRwMLQpzI',
    appId: '1:19763097480:ios:ad01198698c32ff086543d',
    messagingSenderId: '19763097480',
    projectId: 'univalle-news-11560',
    storageBucket: 'univalle-news-11560.appspot.com',
    iosBundleId: 'com.example.univalleNews.RunnerTests',
  );
}
