// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTPJ43hNdTakDkk91zhkCDj-nxCXWSmI',
    appId: '1:524995893021:web:51ec891c9b407a6dde33f4',
    messagingSenderId: '524995893021',
    projectId: 'movilfirebasewe',
    authDomain: 'movilfirebasewe.firebaseapp.com',
    storageBucket: 'movilfirebasewe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv7VkQEC6dPZSgYEecceqYYvWgPMFz97E',
    appId: '1:524995893021:android:546ea457fb09f4fbde33f4',
    messagingSenderId: '524995893021',
    projectId: 'movilfirebasewe',
    storageBucket: 'movilfirebasewe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABxXB7xtmL8f4KL03pE8g0ucX-fQ0s9yI',
    appId: '1:524995893021:ios:fe751ffe79217c7cde33f4',
    messagingSenderId: '524995893021',
    projectId: 'movilfirebasewe',
    storageBucket: 'movilfirebasewe.appspot.com',
    iosBundleId: 'com.example.sprint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABxXB7xtmL8f4KL03pE8g0ucX-fQ0s9yI',
    appId: '1:524995893021:ios:066adb1f9b370116de33f4',
    messagingSenderId: '524995893021',
    projectId: 'movilfirebasewe',
    storageBucket: 'movilfirebasewe.appspot.com',
    iosBundleId: 'com.example.sprint1.RunnerTests',
  );
}
