// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vZBCteKkiUSJFS-Y615dA4Uin2X0LO4',
    appId: '1:1011203086538:web:bb8954a805b2c66eb93c33',
    messagingSenderId: '1011203086538',
    projectId: 'bruna-94cd1',
    authDomain: 'bruna-94cd1.firebaseapp.com',
    storageBucket: 'bruna-94cd1.appspot.com',
    measurementId: 'G-8LPZ557EW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7ImtLhjKe2qvz3u2bzKtyck2krY0NlI',
    appId: '1:1011203086538:android:dc062d3665f28497b93c33',
    messagingSenderId: '1011203086538',
    projectId: 'bruna-94cd1',
    storageBucket: 'bruna-94cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAutnOoc4zjXQaSE_2JQCeGosruF48z_Ck',
    appId: '1:1011203086538:ios:0efcfe1a60f951e2b93c33',
    messagingSenderId: '1011203086538',
    projectId: 'bruna-94cd1',
    storageBucket: 'bruna-94cd1.appspot.com',
    iosBundleId: 'com.example.univalleNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAutnOoc4zjXQaSE_2JQCeGosruF48z_Ck',
    appId: '1:1011203086538:ios:fe41f799a31f00bdb93c33',
    messagingSenderId: '1011203086538',
    projectId: 'bruna-94cd1',
    storageBucket: 'bruna-94cd1.appspot.com',
    iosBundleId: 'com.example.univalleNews.RunnerTests',
  );
}
